// 📦 Shared device-bundle builder used by both `build.ts` and `deploy.ts`.
// Any changes to the firmware output layout should go here so the two stay in sync.
//
// Output layout: dist/<layoutId>/<platform>/<deviceId>/
//   arduino → deja-arduino.ino + config.h
//   pico    → code.py + lib/ + config.json + settings.toml

import fs from 'fs-extra'
import * as path from 'path'
import {
  generateArduinoConfig,
  generateDccExAutomation,
  generatePicoConfig,
  generatePicoSettings,
  type Device,
  type Effect,
  type Loco,
  type Turnout,
} from '@repo/modules'

export type Platform = 'arduino' | 'pico' | 'dcc-ex' | 'esp32'

export interface WriteBundleOptions {
  layoutId: string
  device: Device
  effects: Effect[]
  turnouts: Turnout[]
  /** Layout-wide loco roster — populated by firebase.ts only for dcc-ex devices. */
  locos?: Loco[]
  /** Optional Pico W overrides (deploy-time prompts). Defaults come from env. */
  wifiSsid?: string
  wifiPassword?: string
  mqttBroker?: string
  /** Root of the io package — defaults to process.cwd() (i.e. `io/`). */
  rootDir?: string
}

export interface WriteBundleResult {
  platform: Platform
  /** Device bundle root: dist/<layoutId>/<platform>/<deviceId>/ */
  outDir: string
  /**
   * Directory containing the actual entrypoint source file.
   * - arduino: `<outDir>/deja-arduino/` (Arduino IDE requires a sketch folder matching the .ino name)
   * - pico:    equals `<outDir>` (code.py sits at the root)
   */
  sketchDir: string
  relativeDir: string
}

/** Name of the Arduino sketch folder (must match the .ino filename without extension). */
const ARDUINO_SKETCH_NAME = 'deja-arduino'

/**
 * Device types intentionally excluded from the io/ build.
 * `deja-arduino-led` has its own LED-specific firmware codebase and is not
 * built by this tool. (`dcc-ex` is NOT excluded — it now produces a
 * `myAutomation.h` config file instead of being skipped entirely.)
 */
const EXCLUDED_DEVICE_TYPES = new Set<string>(['deja-arduino-led'])

/** True if this device type is intentionally skipped (has its own source). */
export function isExcludedDeviceType(deviceType: string): boolean {
  return EXCLUDED_DEVICE_TYPES.has(deviceType)
}

/** Map a Firebase device type to a firmware platform, or null if unsupported. */
export function resolvePlatform(deviceType: string): Platform | null {
  if (deviceType === 'deja-arduino') return 'arduino'
  if (deviceType === 'deja-mqtt') return 'pico'
  if (deviceType === 'dcc-ex') return 'dcc-ex'
  // 🪧 Future: map an ESP32 device type here → 'esp32'
  return null
}

/** Generate cross-platform deployment files for Arduino bundles. */
async function generateArduinoCrossPlatformFiles(
  outDir: string,
  deviceId: string,
  effects: Effect[],
  turnouts: Turnout[]
): Promise<void> {
  // 📋 platformio.ini
  const platformioIni = `; PlatformIO Project Configuration File
; Cross-platform deployment: PlatformIO, Arduino CLI, Arduino IDE
; Generated by io/scripts/build.ts for device: ${deviceId}
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = megaatmega2560
src_dir = ${ARDUINO_SKETCH_NAME}
include_dir = ${ARDUINO_SKETCH_NAME}

[env:megaatmega2560]
platform = atmelavr
board = megaatmega2560
framework = arduino

; Library dependencies
lib_deps =
    adafruit/Adafruit PWM Servo Driver Library @ ^2.4.1
    bblanchon/ArduinoJson @ ^7.0.0

; Serial monitor settings
monitor_speed = 115200
monitor_filters = time, log2file

; Upload settings
upload_speed = 115200
`

  await fs.writeFile(path.join(outDir, 'platformio.ini'), platformioIni)

  // 🎯 .arduino-cli.yaml
  const arduinoCliYaml = `board_manager:
  additional_urls:
    - https://arduino.esp8266.com/stable/package_esp8266com_index.json
    - https://adafruit.github.io/arduino-board-index/package_adafruit_index.json

directories:
  data: ~/.arduino15
  downloads: ~/.arduino15/staging
  user: ./

library:
  enable_unsafe_install: false

logging:
  file: ""
  format: text
  level: info

metrics:
  addr: :9090
  enabled: true

sketch:
  always_export_binaries: false

updater:
  enable_notification: true
`

  await fs.writeFile(path.join(outDir, '.arduino-cli.yaml'), arduinoCliYaml)

  // 🙈 .gitignore
  const gitignore = `# Build outputs
.pio/
build/
*.o
*.a
*.elf
*.hex
*.bin

# IDE
.vscode/.browse.c_cpp.db*
.vscode/c_cpp_properties.json
.vscode/launch.json
.vscode/ipch
.DS_Store
*.swp
*.swo
*~

# PlatformIO
.platformio/
.pioenvs/
.piolibdeps/

# Arduino IDE
*.ino.cpp
*.ino.c
*.ino.h

# Generated config (keep template, but ignore user edits)
config.h
!config.default.h
`

  await fs.writeFile(path.join(outDir, '.gitignore'), gitignore)

  // 📖 DEPLOYMENT.md
  const deploymentMd = `# 🚀 ${deviceId} - Cross-Platform Deployment Guide

This Arduino firmware package is configured to deploy seamlessly across **PlatformIO**, **Arduino CLI**, and **Arduino IDE**.

Generated: ${new Date().toISOString()}  
Effects: ${effects.length} | Turnouts: ${turnouts.length}

## 📁 Project Structure

\`\`\`
.
├── ${ARDUINO_SKETCH_NAME}/
│   ├── ${ARDUINO_SKETCH_NAME}.ino       # Main sketch
│   ├── config.h                 # Generated configuration
│   └── config.default.h         # Fallback defaults
├── platformio.ini               # PlatformIO config
├── .arduino-cli.yaml           # Arduino CLI config
├── .gitignore
└── lib/                        # Custom Arduino libraries (optional)
\`\`\`

## 🚀 Quick Start

### Option A: PlatformIO (⭐ Recommended)

\`\`\`bash
# Install
pip install platformio

# Build
platformio run -e megaatmega2560

# Upload
platformio run -e megaatmega2560 --target upload --upload-port /dev/cu.usbserial-*

# Monitor
platformio device monitor --port /dev/cu.usbserial-*
\`\`\`

### Option B: Arduino CLI

\`\`\`bash
# Install CLI
brew install arduino-cli

# Initialize
arduino-cli config init --overwrite
arduino-cli update
arduino-cli core install arduino:avr

# Install libraries
arduino-cli lib install "Adafruit PWM Servo Driver Library"
arduino-cli lib install "ArduinoJson"

# Build
arduino-cli compile --fqbn arduino:avr:mega:cpu=atmega2560 ${ARDUINO_SKETCH_NAME}/${ARDUINO_SKETCH_NAME}.ino

# Upload
arduino-cli upload -p /dev/cu.usbserial-* --fqbn arduino:avr:mega:cpu=atmega2560 ${ARDUINO_SKETCH_NAME}/${ARDUINO_SKETCH_NAME}.ino
\`\`\`

### Option C: Arduino IDE

1. Open **Arduino IDE**
2. Go to **Sketch → Include Library → Manage Libraries**
3. Install:
   - \`Adafruit PWM Servo Driver Library\`
   - \`ArduinoJson\`
4. **File → Open → \`${ARDUINO_SKETCH_NAME}/${ARDUINO_SKETCH_NAME}.ino\`**
5. **Tools → Board → Arduino AVR Boards → Arduino Mega or Mega 2560**
6. **Tools → Processor → ATmega2560 (Mega 2560)**
7. **Tools → Port → \`/dev/cu.usbserial-*\`**
8. Click **Upload** button

## 📦 Generated Configuration

**Effects:** ${effects.length}  
**Turnouts:** ${turnouts.length}

See \`${ARDUINO_SKETCH_NAME}/config.h\` for detailed pin mappings and feature flags.

## 🔌 Serial Communication

**Baud Rate:** 115200

**Command Format:**
\`\`\`json
[
  { "action": "pin", "payload": { "pin": 42, "state": true } },
  { "action": "servo", "payload": { "servo": 0, "value": 90, "current": 45 } },
  { "action": "turnout", "payload": { "turnout": 0, "state": true } }
]
\`\`\`

---

Generated by DEJA.js IO build system
`

  await fs.writeFile(path.join(outDir, 'DEPLOYMENT.md'), deploymentMd)
}

/**
 * Write a firmware bundle to \`dist/<layoutId>/<platform>/<deviceId>/\`.
 * Throws if the device type is unsupported or the platform has no builder yet.
 */
export async function writeDeviceBundle(options: WriteBundleOptions): Promise<WriteBundleResult> {
  const { layoutId, device, effects, turnouts, wifiSsid, wifiPassword, mqttBroker } = options
  const rootDir = options.rootDir ?? process.cwd()

  const platform = resolvePlatform(device.type)
  if (!platform) {
    throw new Error(
      `Unknown device type "${device.type}" for device "${device.id}" — expected Arduino or Pico W`
    )
  }

  const relativeDir = path.join('dist', layoutId, platform, device.id)
  const outDir = path.join(rootDir, relativeDir)
  let sketchDir = outDir
  await fs.emptyDir(outDir)

  if (platform === 'arduino') {
    // Arduino IDE requires the .ino to live inside a folder matching its name,
    // so nest the sketch one level deeper: <outDir>/deja-arduino/deja-arduino.ino
    sketchDir = path.join(outDir, ARDUINO_SKETCH_NAME)
    await fs.copy(path.join(rootDir, 'src/deja-arduino'), sketchDir)
    const configH = generateArduinoConfig({ device, effects, turnouts })
    await fs.writeFile(path.join(sketchDir, 'config.h'), configH)

    // Generate cross-platform deployment files
    await generateArduinoCrossPlatformFiles(outDir, device.id, effects, turnouts)

    console.log(`✅ arduino "${device.id}" → ${relativeDir}/${ARDUINO_SKETCH_NAME}/`)
    console.log(`   📄 ${ARDUINO_SKETCH_NAME}.ino + config.h (${effects.length} effects, ${turnouts.length} turnouts)`)
    console.log(`   ⚙️  platformio.ini, .arduino-cli.yaml, DEPLOYMENT.md`)
  } else if (platform === 'pico') {
    await fs.copy(path.join(rootDir, 'src/deja-pico-w'), outDir)

    const configJson = generatePicoConfig({ device, effects, turnouts, layoutId })
    await fs.writeFile(path.join(outDir, 'config.json'), configJson)

    const resolvedBroker =
      mqttBroker || process.env.MQTT_BROKER || process.env.VITE_MQTT_BROKER || ''
    const settingsToml = generatePicoSettings({
      device,
      effects,
      turnouts,
      layoutId,
      wifiSsid,
      wifiPassword,
      mqttBroker: resolvedBroker,
    })
    await fs.writeFile(path.join(outDir, 'settings.toml'), settingsToml)

    console.log(`✅ pico "${device.id}" → ${relativeDir}/`)
    console.log(`   📄 config.json (${effects.length} effects)`)
    if (wifiSsid) {
      console.log(`   📄 settings.toml (WiFi: ${wifiSsid})`)
    } else {
      console.log(`   📄 settings.toml (WiFi creds empty — edit before deploying)`)
    }
  } else if (platform === 'dcc-ex') {
    // dcc-ex has no sketch to copy — DCC-EX maintains the upstream sketch.
    // We only emit the EXRAIL config that the user copies into their sketch folder.
    if (!options.locos) {
      throw new Error(
        `dcc-ex device "${device.id}" requires locos in WriteBundleOptions — ` +
          `did io/scripts/lib/firebase.ts forget to fetch them?`
      )
    }
    const automationH = generateDccExAutomation({
      device,
      layoutId,
      locos: options.locos,
    })
    await fs.writeFile(path.join(outDir, 'myAutomation.h'), automationH)

    const rosterCount = (automationH.match(/^ROSTER\(/gm) || []).length
    console.log(`✅ dcc-ex "${device.id}" → ${relativeDir}/`)
    console.log(`   📄 myAutomation.h (${rosterCount} ROSTER entries)`)
  } else {
    // 🪧 esp32 support not yet implemented
    throw new Error(`Platform "${platform}" build is not yet implemented`)
  }

  return { platform, outDir, sketchDir, relativeDir }
}
