export * from './guards'
export { default as Login } from './Login.vue'
export { default as Signup } from './Signup.vue'
export { default as ForgotPassword } from './ForgotPassword.vue'
export { default as Signout } from './Signout.vue'
export { default as AccountLinkingDialog } from './AccountLinkingDialog.vue'
export { useAuthProvider } from './useAuthProvider'
export type { ProviderName } from './useAuthProvider'
export { getAuthErrorMessage, isFirebaseAuthError } from './errors'
export type { FirebaseAuthError } from './errors'
export { syncUserProfile } from './syncUserProfile'
