// 🛜 ESP32 WiFi+MQTT config.h generator
// Generates a complete config.h for the deja-esp32-wifi firmware variant.
// Mirrors generateArduinoConfig's hardware feature flags / pin arrays, but
// adds WiFi + MQTT credentials baked in at build time.

import { resolveArduinoConfig } from './arduino-config'
import type { Esp32WifiConfigInput } from './types'

/** 🔒 Escape characters that would break a C string literal. */
function escapeCString(value: string): string {
  return value.replace(/\\/g, '\\\\').replace(/"/g, '\\"')
}

export function generateEsp32WifiConfig(input: Esp32WifiConfigInput): string {
  const { device, effects, turnouts, layoutId } = input

  const outPins = effects
    .filter(e => e.pin !== undefined && e.pin !== null)
    .map(e => e.pin!)

  // 🔢 Same kato-only / sorted-by-turnoutIdx logic as generateArduinoConfig.
  const turnoutPulsers = turnouts
    .filter(t => t.type === 'kato' && t.straight !== undefined && t.divergent !== undefined)
    .slice()
    .sort((a, b) => {
      const ai = a.turnoutIdx ?? Number.POSITIVE_INFINITY
      const bi = b.turnoutIdx ?? Number.POSITIVE_INFINITY
      return ai - bi
    })
    .map(t => `TurnoutPulser(${t.straight}, ${t.divergent})`)

  const sensorPins = input.sensorPins ?? []
  const signalPins = input.signalPins ?? []

  const hasServoTurnouts = turnouts.some(t => t.type === 'servo')
  const hasOutputs = outPins.length > 0
  const hasTurnouts = turnouts.length > 0
  const hasSensors = sensorPins.length > 0
  const hasSignals = signalPins.length > 0
  const enablePwm = input.enablePwm ?? hasServoTurnouts

  const wifiSsid = escapeCString(input.wifiSsid ?? '')
  const wifiPassword = escapeCString(input.wifiPassword ?? '')
  const mqttBroker = escapeCString(input.mqttBroker ?? '')
  const mqttPort = input.mqttPort ?? 1883
  const mqttUsername = escapeCString(input.mqttUsername ?? '')
  const mqttPassword = escapeCString(input.mqttPassword ?? '')
  const topicId = escapeCString(input.topicId ?? 'DEJA')
  const deviceId = escapeCString(device.id)
  const escapedLayoutId = escapeCString(layoutId)

  // 🛠️ Advanced firmware tuning — same resolver as generateArduinoConfig so
  // users editing config in the cloud UI see their overrides on both variants.
  const cfg = resolveArduinoConfig(device.config?.arduino)
  const hasCustomI2cPins =
    typeof cfg.pca9685SdaPin === 'number' && typeof cfg.pca9685SclPin === 'number'
  const pca9685PinDefines = hasCustomI2cPins
    ? `#define PCA9685_SDA_PIN ${cfg.pca9685SdaPin}
#define PCA9685_SCL_PIN ${cfg.pca9685SclPin}
`
    : ''

  return `// 🛜 Generated by @repo/modules/device-config/generateEsp32WifiConfig
// Generated: ${new Date().toISOString()}
// Device: ${device.id}  Layout: ${layoutId}
// Edit WIFI_* / MQTT_* defines below before flashing if they're empty.

#ifndef DEJA_ESP32_WIFI_CONFIG_H
#define DEJA_ESP32_WIFI_CONFIG_H

#include <TurnoutPulser.h>

// 📶 WiFi credentials (baked in at build time)
#define WIFI_SSID "${wifiSsid}"
#define WIFI_PASSWORD "${wifiPassword}"

// 📬 MQTT broker
#define MQTT_BROKER "${mqttBroker}"
#define MQTT_PORT ${mqttPort}
#define MQTT_USERNAME "${mqttUsername}"
#define MQTT_PASSWORD "${mqttPassword}"

// 🏷️ Device identity
#define DEVICE_ID "${deviceId}"
#define LAYOUT_ID "${escapedLayoutId}"
#define TOPIC_ID "${topicId}"

// 🎛️ Feature flags
#define ENABLE_PWM ${enablePwm}
#define ENABLE_OUTPUTS ${hasOutputs}
#define ENABLE_SIGNALS ${hasSignals}
#define ENABLE_TURNOUTS ${hasTurnouts}
#define ENABLE_SENSORS ${hasSensors}

// 📟 Serial
#define BAUD_RATE ${cfg.baudRate}

// 🎛️ Servo tuning (PCA9685 via I2C — ESP32 default SDA=21, SCL=22)
#define SERVOMIN ${cfg.servoMin} // This is the 'minimum' pulse length count (out of 4096)
#define SERVOMAX ${cfg.servoMax} // This is the 'maximum' pulse length count (out of 4096)
#define MIN_PULSE_WIDTH ${cfg.minPulseWidth}
#define MAX_PULSE_WIDTH ${cfg.maxPulseWidth}
#define USMIN ${cfg.usMin}     // This is the rounded 'minimum' microsecond length based on the minimum pulse of 150
#define USMAX ${cfg.usMax}    // This is the rounded 'maximum' microsecond length based on the maximum pulse of 600
#define SERVO_FREQ ${cfg.servoFreq} // Analog servos run at ~50 Hz updates
#define SERVO_COUNT ${cfg.servoCount}
#define PWM_OSCILLATOR_FREQ ${cfg.pwmOscillatorFreq}L
#define PCA9685_ADDRESS 0x${cfg.pca9685Address.toString(16).toUpperCase()}
${pca9685PinDefines}#define SENSOR_DEBOUNCE_MS ${cfg.sensorDebounceMs}

// 📍 Pin arrays
int OUTPINS[] = {${outPins.length > 0 ? ' ' + outPins.join(', ') + ' ' : ''}};
int SIGNALPINS[] = {${signalPins.length > 0 ? ' ' + signalPins.join(', ') + ' ' : ''}};
int SENSORPINS[] = {${sensorPins.length > 0 ? ' ' + sensorPins.join(', ') + ' ' : ''}};

TurnoutPulser turnouts[] = {${turnoutPulsers.length > 0 ? ' ' + turnoutPulsers.join(', ') + ' ' : ''}};

#endif
`
}
