import { describe, it, expect } from 'vitest'
import { generateDccExAutomation } from '../index'
import type { DccExConfigInput, DccExSection } from '../types'
import type { Device } from '../../../layouts/types'
import type { Loco } from '../../../locos/types'

function makeDevice(overrides: Partial<Device> = {}): Device {
  return {
    id: 'test-dccex',
    name: 'Test DCC-EX',
    type: 'dcc-ex',
    ...overrides,
  }
}

function makeLoco(overrides: Partial<Loco> = {}): Loco {
  return {
    id: overrides.id ?? `loco-${overrides.address ?? 3}`,
    address: overrides.address ?? 3,
    name: overrides.name ?? `Eng ${overrides.address ?? 3}`,
    ...overrides,
  }
}

function makeInput(locos: Loco[]): DccExConfigInput {
  return {
    device: makeDevice(),
    layoutId: 'test-layout',
    locos,
  }
}

describe('generateDccExAutomation', () => {
  it('emits the ROSTER section with start/body/end markers when there are locos', () => {
    const result = generateDccExAutomation(
      makeInput([makeLoco({ address: 3, name: 'Eng 3' })]),
    )
    expect(result).toContain(
      '// === ROSTER (auto-generated by DEJA.js — do not edit between markers) ===',
    )
    expect(result).toContain('ROSTER(3,"Eng 3","")')
    expect(result).toContain('// === END ROSTER ===')
  })

  it('omits the ROSTER section entirely when there are no locos', () => {
    const result = generateDccExAutomation(makeInput([]))
    expect(result).toBe('')
    expect(result).not.toContain('ROSTER')
    expect(result).not.toContain('// === END')
  })

  it('emits sections in the order they are registered', () => {
    const sectionA: DccExSection = {
      name: 'ALPHA',
      generate: () => 'alpha-body',
    }
    const sectionB: DccExSection = {
      name: 'BETA',
      generate: () => 'beta-body',
    }
    const result = generateDccExAutomation(makeInput([]), [sectionA, sectionB])
    const alphaIdx = result.indexOf('// === ALPHA')
    const betaIdx = result.indexOf('// === BETA')
    expect(alphaIdx).toBeGreaterThanOrEqual(0)
    expect(betaIdx).toBeGreaterThan(alphaIdx)
    // Sections separated by a blank line.
    expect(result).toContain('// === END ALPHA ===\n\n// === BETA')
  })

  it('skips empty sections and joins remaining ones with a blank line', () => {
    const empty: DccExSection = { name: 'EMPTY', generate: () => '' }
    const real: DccExSection = { name: 'REAL', generate: () => 'real-body' }
    const result = generateDccExAutomation(makeInput([]), [empty, real, empty])
    expect(result).not.toContain('EMPTY')
    expect(result).toContain('// === REAL')
    expect(result).toContain('real-body')
    expect(result).toContain('// === END REAL ===')
  })

  it('returns an empty string when no sections produce output', () => {
    const empty: DccExSection = { name: 'EMPTY', generate: () => '' }
    const result = generateDccExAutomation(makeInput([]), [empty])
    expect(result).toBe('')
  })
})
