import { describe, it, expect } from 'vitest'
import { wrapSection } from '../markers'

describe('wrapSection', () => {
  it('wraps a non-empty body with start and end markers', () => {
    const result = wrapSection('ROSTER', 'ROSTER(3,"Eng 3","")')
    const lines = result.split('\n')
    expect(lines[0]).toBe(
      '// === ROSTER (auto-generated by DEJA.js — do not edit between markers) ===',
    )
    expect(lines[1]).toBe('ROSTER(3,"Eng 3","")')
    expect(lines[2]).toBe('// === END ROSTER ===')
  })

  it('returns an empty string for an empty body', () => {
    expect(wrapSection('ROSTER', '')).toBe('')
  })

  it('preserves multi-line bodies between markers', () => {
    const body = 'line1\nline2\nline3'
    const result = wrapSection('ROSTER', body)
    expect(result).toContain('// === ROSTER')
    expect(result).toContain('line1\nline2\nline3')
    expect(result).toContain('// === END ROSTER ===')
  })
})
