export { default as AppHeader } from './AppHeader.vue'
export { default as ConnectionStatus } from './ConnectionStatus.vue'
export { default as ThrottleLaunchQR } from './ThrottleLaunchQR.vue'
export { default as Logo } from './Logo.vue'
export { default as SplashPage } from './SplashPage.vue'
export { default as NotFoundPage } from './NotFoundPage.vue'
export { default as LocoAvatar } from './LocoAvatar.vue'
export { default as ConsistIndicator } from './Consist/ConsistIndicator.vue'
export { default as ConsistEditor } from './Consist/ConsistEditor.vue'
export { default as Functions } from './Functions/Functions.vue'
export { default as FunctionList } from './Functions/FunctionList.vue'
export { default as FunctionsSpeedDial } from './Functions/SpeedDial.vue'
export { default as SignOut } from './Signout.vue'
export { default as UserProfile } from './UserProfile.vue'
export { default as ViewJson } from './ViewJson.vue'
export { default as SelectLayout } from './SelectLayout.vue'
export { default as LayoutChip } from './LayoutChip.vue'
export { default as TurnoutList } from './Turnouts/TurnoutList.vue'
export { default as TurnoutItem } from './Turnouts/TurnoutItem.vue'
export { default as TurnoutSwitch } from './Turnouts/TurnoutSwitch.vue'
export { default as TurnoutCard } from './Turnouts/TurnoutCard.vue'
export { default as TurnoutButton } from './Turnouts/TurnoutButton.vue'
export { default as TurnoutRaw } from './Turnouts/TurnoutRaw.vue'
export { default as TurnoutTable } from './Turnouts/TurnoutTable.vue'
export { default as TrackPower } from './TrackPower.vue'
export { default as TrackOutputConfig } from './TrackOutputs/TrackOutputConfig.vue'
export { default as PowerDistrictCard } from './TrackOutputs/PowerDistrictCard.vue'
export { default as SignalList } from './SignalList.vue'
export { default as TurnoutLabels } from './Print/TurnoutLabels.vue'
export { default as EffectList } from './Effects/EffectList.vue'
export { default as EffectItem } from './Effects/EffectItem.vue'
export { default as EffectSwitch } from './Effects/EffectSwitch.vue'
export { default as EffectCard } from './Effects/EffectCard.vue'
export { default as EffectButton } from './Effects/EffectButton.vue'
export { default as EffectRaw } from './Effects/EffectRaw.vue'
export { default as EffectTable } from './Effects/EffectTable.vue'
export { default as GuestEffectCard } from './Effects/GuestEffectCard.vue'
export { default as BackgroundDecor } from './BackgroundDecor.vue'
export { default as BackgroundFallingStars } from './BackgroundFallingStars.vue'
export { default as PageBackground } from './backgrounds/PageBackground.vue'
export { default as BackgroundSettings } from './backgrounds/BackgroundSettings.vue'
export { default as BackgroundThumbnail } from './backgrounds/BackgroundThumbnail.vue'
export { backgrounds, getBackgroundById } from './backgrounds/registry'
export type { BackgroundDefinition } from './backgrounds/registry'
export { default as ServerSetupInfo } from './ServerSetupInfo.vue'
export { default as QuickStart } from './QuickStart/QuickStart.vue'
export { default as Stat } from './Stat.vue'
export { default as useColors } from './useColors'
export { default as DeviceStatusItem } from './DeviceStatus/DeviceStatusItem.vue'
export { default as DeviceStatusList } from './DeviceStatus/DeviceStatusList.vue'

// Device Connection
export { DeviceConnectionCard, DeviceConnectionList } from './DeviceConnection'

// Dashboard widgets
export { SystemOverviewStats, CommandActivityChart, DeviceConnectionChart, DeviceTile, QuickConnectPanel, LayoutInfoCard, DashboardEmptyState } from './Dashboard'

// DejaTracker — SVG railroad progress tracker
export { DejaTracker } from './DejaTracker'
export { default as EmptyState } from './EmptyState/EmptyState.vue'
export { default as ModuleList } from './ModuleList/List.vue'
export { default as LocoList } from './Locos/LocoList.vue'
export { default as Menu } from './Menu/Menu.vue'
export { default as NotificationContainer } from './Notifications/NotificationContainer.vue'
export { useNotification, provideNotifications } from './Notifications/useNotification'
export type { Notification, NotificationType, NotifyMethods } from './Notifications/useNotification'
export { OnboardingBanner } from './OnboardingBanner/index'
export { PizzaTracker } from './PizzaTracker/index'
export { default as PromoBanner } from './Promotions/PromoBanner.vue'
export { default as SensorList } from './Sensors/SensorList.vue'
export { default as SensorItem } from './Sensors/SensorItem.vue'
export { default as SensorCard } from './Sensors/SensorCard.vue'
export { default as SensorSwitch } from './Sensors/SensorSwitch.vue'
export { default as SensorTable } from './Sensors/SensorTable.vue'
export * from './animations'
export { appIcons } from './assets/icons'
export type { AppIconName } from './assets/icons'

export { default as FeatureGate } from './FeatureGate.vue'

// Themes
export { createVuetifyThemes, THEME_MODES, THEME_MODE_DEFINITIONS } from './themes'
export type { AppThemeConfig, ThemeMode, ThemeOverrides, ThemeVariables, ThemeModeDefinition } from './themes'
// 🎨 A11y color utilities
export { ensureContrast, ensureUIContrast, ensureAllContrast, meetsContrast, contrastReport, isBadContrast, WCAG } from './themes'
export type { WcagLevel } from './themes'

// Composables
export { useThemeSwitcher } from './composables/useThemeSwitcher'
export { useListControls } from './composables/useListControls'

// PageHeader
export { default as PageHeader } from './PageHeader/PageHeader.vue'

// List Controls
export { default as ListControlBar } from './ListControls/ListControlBar.vue'
export { default as ListSearch } from './ListControls/ListSearch.vue'
export { default as ListViewToggle } from './ListControls/ListViewToggle.vue'
export { default as ListSort } from './ListControls/ListSort.vue'
export { default as ListFilters } from './ListControls/ListFilters.vue'
export { default as ListViewSheet } from './ListControls/ListViewSheet.vue'
export { default as ListSortSheet } from './ListControls/ListSortSheet.vue'
export { default as ListFilterSheet } from './ListControls/ListFilterSheet.vue'
export type { ViewOption, SortOption, FilterOption, ListFilter, ListControlsReturn } from './ListControls/types'
