// AUTO-GENERATED by scripts/generate-icons.mjs — do not edit by hand

export const appIcons = {
  io: new URL('./io.png', import.meta.url).href,
  throttle: new URL('./throttle.png', import.meta.url).href,
  cloud: new URL('./cloud.png', import.meta.url).href,
  monitor: new URL('./monitor.png', import.meta.url).href,
  tour: new URL('./tour.png', import.meta.url).href,
  server: new URL('./server.png', import.meta.url).href,
  deja: new URL('./deja.png', import.meta.url).href,
} as const

export const appLogos = {
  io: new URL('../logos/io.svg', import.meta.url).href,
  throttle: new URL('../logos/throttle.svg', import.meta.url).href,
  cloud: new URL('../logos/cloud.svg', import.meta.url).href,
  monitor: new URL('../logos/monitor.svg', import.meta.url).href,
  tour: new URL('../logos/tour.svg', import.meta.url).href,
  server: new URL('../logos/server.svg', import.meta.url).href,
} as const

export const appColors = {
  io: '#8D00FF',
  throttle: '#43F20D',
  cloud: '#E40DF2',
  monitor: '#1A32E6',
  tour: '#F2B40D',
  server: '#FF0700',
} as const

export type AppIconName = keyof typeof appIcons
export type AppLogoName = keyof typeof appLogos
