export interface WledEffectMeta {
  id: number
  name: string
}

/** All built-in WLED effects. Index = effect ID. Fetched from device at 192.168.86.35. */
export const WLED_EFFECTS: WledEffectMeta[] = [
  { id: 0, name: 'Solid' },
  { id: 1, name: 'Blink' },
  { id: 2, name: 'Breathe' },
  { id: 3, name: 'Wipe' },
  { id: 4, name: 'Wipe Random' },
  { id: 5, name: 'Random Colors' },
  { id: 6, name: 'Sweep' },
  { id: 7, name: 'Dynamic' },
  { id: 8, name: 'Colorloop' },
  { id: 9, name: 'Rainbow' },
  { id: 10, name: 'Scan' },
  { id: 11, name: 'Scan Dual' },
  { id: 12, name: 'Fade' },
  { id: 13, name: 'Theater' },
  { id: 14, name: 'Theater Rainbow' },
  { id: 15, name: 'Running' },
  { id: 16, name: 'Saw' },
  { id: 17, name: 'Twinkle' },
  { id: 18, name: 'Dissolve' },
  { id: 19, name: 'Dissolve Rnd' },
  { id: 20, name: 'Sparkle' },
  { id: 21, name: 'Sparkle Dark' },
  { id: 22, name: 'Sparkle+' },
  { id: 23, name: 'Strobe' },
  { id: 24, name: 'Strobe Rainbow' },
  { id: 25, name: 'Strobe Mega' },
  { id: 26, name: 'Blink Rainbow' },
  { id: 27, name: 'Android' },
  { id: 28, name: 'Chase' },
  { id: 29, name: 'Chase Random' },
  { id: 30, name: 'Chase Rainbow' },
  { id: 31, name: 'Chase Flash' },
  { id: 32, name: 'Chase Flash Rnd' },
  { id: 33, name: 'Rainbow Runner' },
  { id: 34, name: 'Colorful' },
  { id: 35, name: 'Traffic Light' },
  { id: 36, name: 'Sweep Random' },
  { id: 37, name: 'Chase 2' },
  { id: 38, name: 'Aurora' },
  { id: 39, name: 'Stream' },
  { id: 40, name: 'Scanner' },
  { id: 41, name: 'Lighthouse' },
  { id: 42, name: 'Fireworks' },
  { id: 43, name: 'Rain' },
  { id: 44, name: 'Tetrix' },
  { id: 45, name: 'Fire Flicker' },
  { id: 46, name: 'Gradient' },
  { id: 47, name: 'Loading' },
  { id: 48, name: 'Rolling Balls' },
  { id: 49, name: 'Fairy' },
  { id: 50, name: 'Two Dots' },
  { id: 51, name: 'Fairytwinkle' },
  { id: 52, name: 'Running Dual' },
  { id: 53, name: 'RSVD' },
  { id: 54, name: 'Chase 3' },
  { id: 55, name: 'Tri Wipe' },
  { id: 56, name: 'Tri Fade' },
  { id: 57, name: 'Lightning' },
  { id: 58, name: 'ICU' },
  { id: 59, name: 'Multi Comet' },
  { id: 60, name: 'Scanner Dual' },
  { id: 61, name: 'Stream 2' },
  { id: 62, name: 'Oscillate' },
  { id: 63, name: 'Pride 2015' },
  { id: 64, name: 'Juggle' },
  { id: 65, name: 'Palette' },
  { id: 66, name: 'Fire 2012' },
  { id: 67, name: 'Colorwaves' },
  { id: 68, name: 'Bpm' },
  { id: 69, name: 'Fill Noise' },
  { id: 70, name: 'Noise 1' },
  { id: 71, name: 'Noise 2' },
  { id: 72, name: 'Noise 3' },
  { id: 73, name: 'Noise 4' },
  { id: 74, name: 'Colortwinkles' },
  { id: 75, name: 'Lake' },
  { id: 76, name: 'Meteor' },
  { id: 77, name: 'Meteor Smooth' },
  { id: 78, name: 'Railway' },
  { id: 79, name: 'Ripple' },
  { id: 80, name: 'Twinklefox' },
  { id: 81, name: 'Twinklecat' },
  { id: 82, name: 'Halloween Eyes' },
  { id: 83, name: 'Solid Pattern' },
  { id: 84, name: 'Solid Pattern Tri' },
  { id: 85, name: 'Spots' },
  { id: 86, name: 'Spots Fade' },
  { id: 87, name: 'Glitter' },
  { id: 88, name: 'Candle' },
  { id: 89, name: 'Fireworks Starburst' },
  { id: 90, name: 'Fireworks 1D' },
  { id: 91, name: 'Bouncing Balls' },
  { id: 92, name: 'Sinelon' },
  { id: 93, name: 'Sinelon Dual' },
  { id: 94, name: 'Sinelon Rainbow' },
  { id: 95, name: 'Popcorn' },
  { id: 96, name: 'Drip' },
  { id: 97, name: 'Plasma' },
  { id: 98, name: 'Percent' },
  { id: 99, name: 'Ripple Rainbow' },
  { id: 100, name: 'Heartbeat' },
  { id: 101, name: 'Pacifica' },
  { id: 102, name: 'Candle Multi' },
  { id: 103, name: 'Solid Glitter' },
  { id: 104, name: 'Sunrise' },
  { id: 105, name: 'Phased' },
  { id: 106, name: 'Twinkleup' },
  { id: 107, name: 'Noise Pal' },
  { id: 108, name: 'Sine' },
  { id: 109, name: 'Phased Noise' },
  { id: 110, name: 'Flow' },
  { id: 111, name: 'Chunchun' },
  { id: 112, name: 'Dancing Shadows' },
  { id: 113, name: 'Washing Machine' },
  { id: 114, name: 'Rotozoomer' },
  { id: 115, name: 'Blends' },
  { id: 116, name: 'TV Simulator' },
  { id: 117, name: 'Dynamic Smooth' },
  { id: 118, name: 'Spaceships' },
  { id: 119, name: 'Crazy Bees' },
  { id: 120, name: 'Ghost Rider' },
  { id: 121, name: 'Blobs' },
  { id: 122, name: 'Scrolling Text' },
  { id: 123, name: 'Drift Rose' },
  { id: 124, name: 'Distortion Waves' },
  { id: 125, name: 'Soap' },
  { id: 126, name: 'Octopus' },
  { id: 127, name: 'Waving Cell' },
  { id: 128, name: 'Pixels' },
  { id: 129, name: 'Pixelwave' },
  { id: 130, name: 'Juggles' },
  { id: 131, name: 'Matripix' },
  { id: 132, name: 'Gravimeter' },
  { id: 133, name: 'Plasmoid' },
  { id: 134, name: 'Puddles' },
  { id: 135, name: 'Midnoise' },
  { id: 136, name: 'Noisemeter' },
  { id: 137, name: 'Freqwave' },
  { id: 138, name: 'Freqmatrix' },
  { id: 139, name: 'GEQ' },
  { id: 140, name: 'Waterfall' },
  { id: 141, name: 'Freqpixels' },
  { id: 142, name: 'RSVD' },
  { id: 143, name: 'Noisefire' },
  { id: 144, name: 'Puddlepeak' },
  { id: 145, name: 'Noisemove' },
  { id: 146, name: 'Noise2D' },
  { id: 147, name: 'Perlin Move' },
  { id: 148, name: 'Ripple Peak' },
  { id: 149, name: 'Firenoise' },
  { id: 150, name: 'Squared Swirl' },
  { id: 151, name: 'RSVD' },
  { id: 152, name: 'DNA' },
  { id: 153, name: 'Matrix' },
  { id: 154, name: 'Metaballs' },
  { id: 155, name: 'Freqmap' },
  { id: 156, name: 'Gravcenter' },
  { id: 157, name: 'Gravcentric' },
  { id: 158, name: 'Gravfreq' },
  { id: 159, name: 'DJ Light' },
  { id: 160, name: 'Funky Plank' },
  { id: 161, name: 'RSVD' },
  { id: 162, name: 'Pulser' },
  { id: 163, name: 'Blurz' },
  { id: 164, name: 'Drift' },
  { id: 165, name: 'Waverly' },
  { id: 166, name: 'Sun Radiation' },
  { id: 167, name: 'Colored Bursts' },
  { id: 168, name: 'Julia' },
  { id: 169, name: 'RSVD' },
  { id: 170, name: 'RSVD' },
  { id: 171, name: 'RSVD' },
  { id: 172, name: 'Game Of Life' },
  { id: 173, name: 'Tartan' },
  { id: 174, name: 'Polar Lights' },
  { id: 175, name: 'Swirl' },
  { id: 176, name: 'Lissajous' },
  { id: 177, name: 'Frizzles' },
  { id: 178, name: 'Plasma Ball' },
  { id: 179, name: 'Flow Stripe' },
  { id: 180, name: 'Hiphotic' },
  { id: 181, name: 'Sindots' },
  { id: 182, name: 'DNA Spiral' },
  { id: 183, name: 'Black Hole' },
  { id: 184, name: 'Wavesins' },
  { id: 185, name: 'Rocktaves' },
  { id: 186, name: 'Akemi' },
]
