// 🚂 DCC-EX config.h generator
//
// Minimal config.h for a USB-only Arduino Mega + motor shield build. DCC-EX
// defaults cover everything else (LCD, Ethernet, WiFi, defaults all off), so
// all we need to emit is the motor shield selection.
//
// More complex deployments (WiFi/Ethernet, OLED, multi-track config) should
// be built with the upstream DCC-EX workflow, not the DEJA.js io tool.

import type { Device } from '../../layouts/types'

/** Supported motor shield choices for DEJA.js-built DCC-EX bundles. */
export type DccExMotorShield = 'standard' | 'ex8874'

/** Map the UI-friendly shield value to the exact DCC-EX macro name. */
export const DCC_EX_MOTOR_SHIELD_MACROS: Record<DccExMotorShield, string> = {
  standard: 'STANDARD_MOTOR_SHIELD',
  ex8874: 'EX8874_SHIELD',
}

/** Map shield value to a human label used in comments / logs. */
export const DCC_EX_MOTOR_SHIELD_LABELS: Record<DccExMotorShield, string> = {
  standard: 'Standard Arduino Motor Shield R3',
  ex8874: 'DCC-EX EX-MotorShield8874',
}

export interface DccExConfigHInput {
  device: Device
  layoutId: string
  motorShield: DccExMotorShield
}

export function generateDccExConfig(input: DccExConfigHInput): string {
  const { device, layoutId, motorShield } = input
  const macro = DCC_EX_MOTOR_SHIELD_MACROS[motorShield]
  const label = DCC_EX_MOTOR_SHIELD_LABELS[motorShield]

  return `// 🚂 Generated by DEJA.js — DCC-EX config.h
// Device: ${device.id}  Layout: ${layoutId}
// Motor shield: ${label}
// Generated: ${new Date().toISOString()}
//
// This file intentionally contains only the motor-shield selection.
// DCC-EX supplies defaults for every other feature (LCD, WiFi, Ethernet,
// OLED, etc.) when their respective defines are absent. If you need any of
// those, use the upstream DCC-EX build workflow instead of \`pnpm deploy\`.

#define MOTOR_SHIELD_TYPE ${macro}
`
}
