// 🪧 Section marker helper for DCC-EX myAutomation.h
//
// Wraps a section body in `// === NAME ... ===` / `// === END NAME ===`
// comment delimiters so users can safely hand-edit the rest of the file
// while DEJA.js owns whatever lives between the markers.

/**
 * Wrap a section body in DEJA.js-owned marker comments.
 * Returns `''` for an empty body so the orchestrator never emits an empty
 * marker pair into the output file.
 */
export function wrapSection(name: string, body: string): string {
  if (!body) return ''
  return [
    `// === ${name} (auto-generated by DEJA.js — do not edit between markers) ===`,
    body,
    `// === END ${name} ===`,
  ].join('\n')
}
